#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-woodstox-core
Version  : 5.0.3
Release  : 2
URL      : https://github.com/FasterXML/woodstox/archive/woodstox-core-5.0.3.tar.gz
Source0  : https://github.com/FasterXML/woodstox/archive/woodstox-core-5.0.3.tar.gz
Source1  : https://repo1.maven.org/maven2/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar
Source2  : https://repo1.maven.org/maven2/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-woodstox-core-data = %{version}-%{release}

%description
# Overview
The gold standard Stax XML API implementation. Now at Github.
## Status

%package data
Summary: data components for the mvn-woodstox-core package.
Group: Data

%description data
data components for the mvn-woodstox-core package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar
/usr/share/java/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.pom
